accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('account/', views.QuizResultListView.as_view(), name='account'),
    path('account/<int:pk>/', views.QuizResultDetailView.as_view(), name='results'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('quiz.urls', namespace='quiz')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('nested_admin/', include('nested_admin.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='home'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category'),
    path('quiz/<slug:slug>/', views.QuizView.as_view(), name='quiz'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from quiz.models import Quiz


class UserQuizResult(models.Model):
    user = models.ForeignKey(
        User,
        related_name='quiz_results',
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
    )
    quiz = models.ForeignKey(
        Quiz,
        related_name='quiz_results',
        on_delete=models.CASCADE,
        verbose_name='Тест',
    )
    question_counts = models.PositiveSmallIntegerField(
        'Количество вопросов в тесте',
    )
    correct_answers = models.PositiveSmallIntegerField(
        'Количество верных ответов',
    )
    created_at = models.DateTimeField(
        'Дата прохождения теста',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at',]
        verbose_name = 'Результат теста'
        verbose_name_plural = 'Результаты тестов'

    def __str__(self):
        return f'{self.user.username} - {self.quiz.name} - {self.created_at.strftime("%d.%m.%Y %H:%m")}'

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from .models import UserQuizResult


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class QuizResultListView(LoginRequiredMixin, ListView):
    model = UserQuizResult

    context_object_name = 'quizzes'
    paginate_by = 20


class QuizResultDetailView(LoginRequiredMixin, DetailView):
    model = UserQuizResult

    context_object_name = 'quiz'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quiz_id = self.kwargs['pk']
        quiz = self.model.objects.get(id=quiz_id)
        percent_correct = quiz.correct_answers / quiz.question_counts * 100
        context['percent_correct'] = percent_correct

        return context

templates/accounts/userquizresult_detail.html
{% extends "base.html" %}

{% block title %}{{ quiz.name }}{% endblock title %}

{% block content %}
    <div class="row">
        <h3>Результат прохождения теста {{ quiz.quiz.name }}:</h3>
    </div>
        <p>Правильные ответы: {{ quiz.correct_answers }} из {{ quiz.question_counts }}</p>
        <p>Процент правильных ответов: {{ percent_correct }}%</p>
    <a class="btn btn-danger" href="{% url 'accounts:account' %}">К списку пройденных тестов</a>
{% endblock content %}

templates/accounts/userquizresult_list.html
{%  extends 'base.html' %}

{% block title %}Личный кабинет {{ user.username }}{% endblock title %}

{% block content %}
    <h3>Тесты пройденные пользователем {{ user.username }}:</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Категория</th>
          <th scope="col">Тест</th>
          <th scope="col">Дата</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      {% for quiz in quizzes %}
            <tr>
                <td>{{ quiz.quiz.category.name }}</td>
                <td>{{ quiz.quiz.name }}</td>
                <td>{{ quiz.created_at|date:'d.m.Y H:i' }}</td>
                <td><a class="btn btn-danger" href="{% url 'accounts:results' quiz.id %}">Подробнее</a></td>
            </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock content %}