config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('quiz.urls', namespace='quiz')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('nested_admin/', include('nested_admin.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='home'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category'),
    path('quiz/<slug:slug>/', views.QuizView.as_view(), name='quiz'),
]

quiz/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        'Дата обновления',
        auto_now=True
    )

    class Meta:
        abstract = True


class Category(BaseModel):
    name = models.CharField(
        'Название категории',
        max_length=100
    )
    slug = models.SlugField(
        max_length=250
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Quiz(BaseModel):
    name = models.CharField(
        'Название теста',
        max_length=250,
        unique=True
    )
    slug = models.SlugField(
        max_length=250
    )
    category = models.ForeignKey(
        Category,
        related_name='quizzes',
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Категория'
    )

    class Meta:
        ordering = ['-created_at',]
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

    def __str__(self):
        return self.name


class Question(BaseModel):
    quiz = models.ForeignKey(
        Quiz,
        related_name='questions',
        on_delete=models.CASCADE,
        verbose_name='Тест',
    )
    question = models.TextField(
        'Вопрос',
        max_length=1000
    )

    class Meta:
        ordering = ['-created_at',]
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.question

    def get_answers(self):
        return [
            (answer.id, answer.answer) for answer in self.answers.all()
        ]


class Answer(BaseModel):
    question = models.ForeignKey(
        Question,
        related_name='answers',
        on_delete=models.CASCADE,
        verbose_name='Ответ'
    )
    answer = models.CharField(
        'Ответ',
        max_length=250
    )
    is_correct = models.BooleanField(
        'Правильный ответ',
        default=False
    )

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Oтветы'

    def __str__(self):
        return self.answer

quiz/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [answer for answer in question.get_answers()]
        self.fields['answers'] = forms.MultipleChoiceField(
            choices=choice_list,
            widget=CheckboxSelectMultiple
        )

quiz/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, FormView
from django.contrib.auth.models import User

from .models import Category, Question, Quiz
from accounts.models import UserQuizResult
from .forms import QuestionForm


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    context_object_name = 'categories'
    paginate_by =  20


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    paginate_by = 20


class QuizView(LoginRequiredMixin, FormView):
    form_class = QuestionForm
    template_name = 'quiz/question.html'
    
    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, slug=self.kwargs['slug'])
        self.sitting = self.load_sitting()
        return super(QuizView, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=QuestionForm):
        self.question = self.get_next_question()
        self.progress = self.get_sitting_progress()

        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizView, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        self.user_form_valid(form)
        if not self.request.session[f'{self.request.user.id}_question_list']:
            return self.final_result()
        self.request.POST = {}
        return super(QuizView, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizView, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def load_sitting(self):
        if f'{self.request.user.id}_question_list' in self.request.session:
            return self.request.session[f'{self.request.user.id}_question_list']
        else:
            return self.new_quiz_session()

    def new_quiz_session(self):
        self.request.session.set_expiry(259200)
        questions = self.quiz.questions.all()
        question_list = [question.id for question in questions]

        self.request.session[f'{self.request.user.id}_question_list'] = question_list
        self.request.session[f'{self.request.user.id}_question_data'] = dict(
            incorrect_questions=[],
            order=question_list,
        )
        return self.request.session[f'{self.request.user.id}_question_list']
    #
    def get_next_question(self):
        next_question_id = self.request.session[f'{self.request.user.id}_question_list'][0]
        return Question.objects.get(id=next_question_id)
    #
    def get_sitting_progress(self):
        total = len(self.request.session[f'{self.request.user.id}_question_data']['order'])
        answered = total - len(self.request.session[f'{self.request.user.id}_question_list'])
        return (answered, total)

    def user_form_valid(self, form):
        guess = [
            int(user_answer) for user_answer in form.cleaned_data['answers']
        ]
        correct_answers = [
            answer.id for answer in self.question.answers.filter(is_correct=True)
        ]


        if guess == correct_answers:
            self.session_score(self.request.session, 1, 1)
        else:
            self.request.session[
                f'{self.request.user.id}_question_data'
            ]['incorrect_questions'].append(self.question.id)
            self.session_score(self.request.session, 0, 1)


        self.previous = {}

        self.request.session[
            f'{self.request.user.id}_question_list'
        ] = self.request.session[f'{self.request.user.id}_question_list'][1:]

    def final_result(self):
        incorrect_question_ids = self.request.session[
            f'{self.request.user.id}_question_data'
        ]['incorrect_questions']
        incorrect_questions = []
        if incorrect_question_ids:
            for id in incorrect_question_ids:
                incorrect_questions.append(Question.objects.get(id=id))

        session_score, session_possible = self.session_score(
            self.request.session)

        percent_correct = session_score / session_possible * 100

        results = {
            'incorrect_questions': incorrect_questions,
            'session_score': session_score,
            'possible': session_possible,
            'percent_correct': percent_correct,

        }

        UserQuizResult.objects.create(
            user=get_object_or_404(User, id=self.request.user.id),
            quiz=self.quiz,
            question_counts=session_possible,
            correct_answers=session_score
        )

        del self.request.session[f'{self.request.user.id}_question_list']

        results['previous'] = self.previous

        del self.request.session[f'{self.request.user.id}_question_data']
        self.request.session["session_score"], self.request.session["session_score_possible"] = 0, 0
        return render(self.request, 'quiz/result.html', results)

    def session_score(self, session, to_add=0, possible=0):
        if "session_score" not in session:
            session["session_score"], session["session_score_possible"] = 0, 0
        if possible > 0:
            session["session_score"] += to_add
            session["session_score_possible"] += possible

        return session["session_score"], session["session_score_possible"]

templates/quiz/category_detail.html
{%  extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock title %}

{% block content %}
    <h3>{{ category.name }}:</h3>
        <ul>
            {% for quiz in category.quizzes.all %}
                <li><a href="{% url 'quiz:quiz' quiz.slug %}">{{ quiz.name }}</a></li>
            {% endfor %}
        </ul>
    <a class="btn btn-danger" href="{% url 'quiz:home' %}">К списку категорий</a>
{% endblock content %}

templates/quiz/category_list.html
{%  extends 'base.html' %}

{% block title %}Выберите категорию{% endblock title %}

{% block content %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Категория</th>
          <th scope="col">Количество тестов</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.quizzes.count }}</td>
                <td><a class="btn btn-danger" href="{% url 'quiz:category' category.slug %}">Перейти</a></td>
            </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock content %}

templates/quiz/question.html
{% extends "base.html" %}

{% block title %}{{ quiz.name }}{% endblock title %}

{% block content %}
    {% if question %}

        {% if progress %}
            <div style="float: right;">
                Вопрос {{progress.0|add:1}} из {{ progress.1 }}
            </div>
        {% endif %}

        <p>
            <small class="muted">Категория:</small>
            <strong>{{ quiz.category }}</strong>
        </p>
        <p class="lead">{{ question.question }}</p>
        <form action="" method="POST">
            {% csrf_token %}
            <input type=hidden name="question_id" value="{{ question_id }}">
            <ul class="list-group">
                {% for answer in form.answers %}
                    <li class="list-group-item">
                        {{ answer }}
                    </li>
                {% endfor %}
            </ul>
            <br>
            <input type="submit" value="Подтвердить" class="btn btn-large btn-block btn-success">
        </form>
    {% endif %}
{% endblock content %}

templates/quiz/result.html
{% extends "base.html" %}

{% block title %}{{ quiz.name }}{% endblock title %}

{% block content %}
    <div class="row">
        <h3>Результат прохождения теста:</h3>
    </div>
    {% if possible %}
        <p>Правильные ответы: {{ session_score }} из {{ possible }}</p>
        <p>Процент правильных ответов: {{ percent_correct }}%</p>
    {% endif %}
    {% if incorrect_questions %}
        <h4>Вопросы на которые даны неверные ответы:</h4>
        <ul>
            {% for question in incorrect_questions %}
                <li>{{ question.question }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <a class="btn btn-danger" href="{% url 'quiz:home' %}">К списку категорий</a>
{% endblock content %}